apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
- namespace.yaml
- etcd-service.yaml
- etcd-statefulset.yaml
- patroni-configmap.yaml
- postgres-service.yaml
- postgres-statefulset.yaml